# Generated by Django 3.2 on 2023-06-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_shipping_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='weight_kg',
        ),
    ]
