# Generated by Django 3.2 on 2023-06-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_sizes', '0005_productsize_category'),
        ('checkout', '0006_auto_20230614_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_sizes.productsize'),
        ),
    ]
