# Generated by Django 3.2 on 2023-05-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0002_size_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
