# Generated by Django 3.2 on 2023-05-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0003_auto_20230505_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
