# Generated by Django 3.2 on 2023-05-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230516_1141'),
        ('sizes', '0004_delete_productsize'),
        ('product_sizes', '0003_remove_productsize_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('product', 'size')},
        ),
    ]
