# Generated by Django 3.2 on 2023-04-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230422_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_colors',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
