# Generated by Django 3.2 on 2023-05-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
    ]
